name: Docker Build & Push

on:
  push:
    branches:
      - main  # oder dein Standardbranch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Logge dich bei GHCR ein
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.HHS }}

      - name: Docker Image bauen
        run: |
          docker build -t ghcr.io/hennes617/meshwetter:latest .

      - name: Docker Image pushen
        run: |
          docker push ghcr.io/hennes617/meshwetter:latest
